### ISSUE TITLE
SERVICE KAtmanı

### ISSUE THREAD

**Issue by fatihGunalp** [fatihGunalp/MVCBlogProject#4]
MODEL, DAL katmanları bitirildikten sonra CORE katmanı içerisinde tanımlanan Service isimli klasördeki ICoreService'den türetilecek classlar içerisinde metotlar implement edilerek Crud işlemleri tanımlanacak.

**Comment by fatihGunalp** [comment]
@omerfbal 
- [ ] UserService

- [ ] ArticleService

- [ ] CategoryService

- [ ] CommentService

- [ ] TagService

**Comment by omerfbal** [comment]
Servisler oluşturuldu.
